# Site settings
name: Ganesh Gundu
title: Ganesh Gundu | Lead Software Engineer
description: Design-minded Software Engineer focused on building full stack web and mobile experiences.
url: https://ganesh76.github.io/
baseurl: ""
email: ganesh.g.cse@gmail.com
cover: https://ganesh76.github.io/img/og.png
logo: https://ganesh76.github.io/img/emojis/technologist.png
resume: https://ganesh76.github.io/resume.pdf
social:
  - title: email
    url: mailto:ganesh.g.cse@gmail.com
  - title: github
    url: https://github.com/ganesh76
  - title: linkedin
    url: https://www.linkedin.com/in/gganeshlink/
  - title: playstore 
    url: https://play.google.com/store/apps/developer?id=G+Ganesh

# Build settings
markdown: kramdown

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gemspec"
  - "README.md"
  - "node_modules"
  - "build"
  - "gulpfile.js"
  - "package.json"

keep_files:
  - "CNAME"
  - ".git"
  - ".gitignore"

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
